# Generated by Django 4.1.4 on 2023-03-27 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlRatingMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.TextField()),
                ('effectiveness', models.TextField()),
                ('formula', models.TextField()),
                ('overall_rating', models.TextField()),
                ('control_score', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField(blank=True, null=True)),
                ('risk_appetite_statement', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('responisble_department_id', models.TextField(blank=True, null=True)),
                ('key_risk_indicators', models.TextField(blank=True, null=True)),
                ('risk_appetite', models.TextField(blank=True, null=True)),
                ('date_of_assessment', models.TextField(blank=True, null=True)),
                ('kri_reporting', models.TextField(blank=True, null=True)),
                ('previous_assessment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likehood', models.TextField()),
                ('impact', models.TextField()),
                ('combine', models.TextField()),
                ('score', models.TextField()),
                ('likehood_rate', models.TextField()),
                ('impact_rate', models.TextField()),
                ('score_rate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=500)),
                ('departments', models.TextField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskPrioritization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.TextField()),
                ('rating', models.TextField()),
                ('priority', models.TextField()),
                ('color_code', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RiskRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=123)),
                ('file', models.FileField(blank=True, upload_to='Risk_file')),
                ('status', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('consequence', models.TextField(blank=True, null=True)),
                ('category', models.TextField(blank=True, null=True)),
                ('function_owner', models.TextField(blank=True, null=True)),
                ('risk_owner', models.TextField(blank=True, null=True)),
                ('risk_champion', models.TextField(blank=True, null=True)),
                ('inherent_risk_rating_likehood', models.TextField(blank=True, null=True)),
                ('inherent_risk_rating_impact', models.TextField(blank=True, null=True)),
                ('inherent_risk_rating_rating', models.TextField(blank=True, null=True)),
                ('control_description', models.TextField(blank=True, null=True)),
                ('control_design_assessement', models.TextField(blank=True, null=True)),
                ('control_effectiveness_assessement', models.TextField(blank=True, null=True)),
                ('overall_control_rating', models.TextField(blank=True, null=True)),
                ('residual_risk_scoring_score', models.TextField(blank=True, null=True)),
                ('risk_responses', models.TextField(blank=True, null=True)),
                ('treatment_required', models.TextField(blank=True, null=True)),
                ('action_plan', models.TextField(blank=True, null=True)),
                ('action_plan_owner', models.TextField(blank=True, null=True)),
                ('implementation_date', models.TextField(blank=True, null=True)),
                ('parent_id', models.IntegerField(blank=True, null=True)),
                ('previous_assessment', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('assessment_date', models.DateField(blank=True, null=True)),
                ('next_review_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='master_app.companysetup')),
                ('departments', models.ManyToManyField(to='master_app.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
