# Generated by Django 4.1.4 on 2023-05-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='sub_department',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
