# Generated by Django 4.1.4 on 2023-06-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk_app', '0002_riskregister_sub_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskregister',
            name='review_status',
            field=models.TextField(blank=True, default='Draft', null=True),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Risk_file'),
        ),
        migrations.AlterField(
            model_name='riskregister',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
