# Generated by Django 4.1.4 on 2023-04-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlobjective',
            name='title',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
