# Generated by Django 4.1.4 on 2023-04-20 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0002_controlobjective_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlobjective',
            name='frequency',
        ),
    ]
