# Generated by Django 4.1.4 on 2023-04-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0001_initial'),
        ('master_app', '0003_remove_controlobjective_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlobjective',
            name='policy',
            field=models.ManyToManyField(to='policy_app.policy'),
        ),
    ]
