# Generated by Django 4.1.4 on 2023-05-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0004_controlobjective_policy'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belogTo', models.TextField()),
                ('docId', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
