# Generated by Django 4.1.4 on 2023-06-28 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0005_doccomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlobjective',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='controlobjective',
            name='title',
        ),
        migrations.AddField(
            model_name='controlobjective',
            name='frequency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
