# Generated by Django 4.1.4 on 2023-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0005_regulatorylaws_policy'),
        ('master_app', '0006_remove_controlobjective_policy_and_more'),
    ]

    operations = [
        # migrations.AddField(
            # model_name='companysetup',
            # name='departments',
            # field=models.ManyToManyField(to='master_app.department'),
        # ),
        migrations.AddField(
            model_name='controlobjective',
            name='policy',
            field=models.ManyToManyField(to='policy_app.policy'),
        ),
        migrations.AddField(
            model_name='controlobjective',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
