# Generated by Django 4.1.4 on 2023-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0007_companysetup_departments_controlobjective_policy_and_more'),
    ]

#    operations = [
 #       migrations.AddField(
  #          model_name='companysetup',
   #         name='departments',
    #        field=models.ManyToManyField(to='master_app.department'),
     #   ),
    #]
