# Generated by Django 4.1.4 on 2023-06-08 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=500)),
                ('departments', models.TextField(blank=True, max_length=5000, null=True)),
                ('state', models.CharField(blank=True, default='Draft', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=123)),
                ('file', models.FileField(blank=True, upload_to='Audit_Plan_File')),
                ('approved_commit', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=500)),
                ('allocated_manager', models.CharField(blank=True, max_length=30)),
                ('state', models.CharField(blank=True, default='Draft', max_length=30)),
                ('duration_days', models.CharField(blank=True, max_length=30)),
                ('duration_hours', models.CharField(blank=True, max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('objective', models.TextField(blank=True, max_length=500)),
                ('description_approval', models.TextField(blank=True)),
                ('department_head', models.TextField(blank=True, max_length=500)),
                ('total_staff', models.TextField(blank=True, max_length=500)),
                ('approved_policies', models.TextField(blank=True, max_length=500)),
                ('audit_observation', models.TextField(blank=True, max_length=500)),
                ('open_issues', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AuditEngagementAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=123)),
                ('content', models.FileField(upload_to='audit_files')),
            ],
        ),
        migrations.CreateModel(
            name='AuditProgramRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AuditProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('title_of_procedure', models.TextField(blank=True)),
                ('summary_of_procedure', models.TextField(blank=True)),
                ('design_assessment_result', models.TextField(blank=True)),
                ('operating_assessment_result', models.TextField(blank=True)),
                ('audit_process_result', models.TextField(blank=True)),
                ('issue_check', models.BooleanField(blank=True, default=False)),
                ('control_issue', models.TextField(blank=True)),
                ('action_plan', models.CharField(blank=True, max_length=300)),
                ('our_reputation', models.TextField(blank=True, null=True)),
                ('our_observation', models.CharField(blank=True, max_length=300)),
                ('management_response', models.CharField(blank=True, max_length=300)),
                ('implications', models.CharField(blank=True, max_length=300)),
                ('approval_status', models.TextField(blank=True, default='Draft')),
                ('agree_date_action_plan', models.DateField(blank=True, null=True)),
                ('audit_engagement', models.ForeignKey(blank=True, default=False, on_delete=django.db.models.deletion.CASCADE, related_name='aduit_engagment_program', to='audit_app.auditengagement')),
            ],
        ),
    ]
