# Generated by Django 4.1.4 on 2023-04-01 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0001_initial'),
    ]

    operations = [
#        migrations.AddField(
#            model_name='auditprogram',
#            name='our_observation',
#            field=models.CharField(blank=True, max_length=300),
#        ),
    ]
