# Generated by Django 4.1.4 on 2023-04-04 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0002_auditprogram_our_observation'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprogram',
            name='reviews',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='controls',
            field=models.ManyToManyField(blank=True, to='policy_app.control'),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='implications',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
 