# Generated by Django 4.1.4 on 2023-05-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0004_auditprogram_implications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_description', models.TextField()),
                ('our_observation', models.TextField(blank=True, null=True)),
            ],
        ),
       # migrations.AddField(
        #    model_name='auditprogram',
         #   name='agree_date_action_plan',
          #  field=models.DateField(blank=True, null=True),
          # ),
       # migrations.AddField(
        #    model_name='auditprogram',
         #   name='approval_status',
          #  field=models.TextField(blank=True, default='created'),
       # ),
        migrations.AlterField(
            model_name='auditprogram',
            name='our_reputation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
