# Generated by Django 4.1.4 on 2023-06-28 07:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0006_remove_controlobjective_policy_and_more'),
        ('risk_app', '0003_riskregister_review_status_alter_riskregister_file_and_more'),
        ('audit_app', '0006_auditprogram_agree_date_action_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Observations',
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='implications',
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='our_description',
        ),
        migrations.RemoveField(
            model_name='auditprogram',
            name='reviews',
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='annual_plan',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='annual_plan', to='audit_app.annualplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditengagement',
            name='department',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='departmentId', to='master_app.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditengagementattachment',
            name='ticket',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, related_name='auditengagement_attachment', to='audit_app.auditengagement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='file_name',
            field=models.CharField(blank=True, max_length=123),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='files',
            field=models.FileField(blank=True, upload_to='audit_files'),
        ),
        migrations.AddField(
            model_name='auditprogram',
            name='risk_tagging',
            field=models.ManyToManyField(blank=True, to='risk_app.riskregister'),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='approval_status',
            field=models.TextField(blank=True, default='Draft'),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='audit_process_result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='control_issue',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='design_assessment_result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='operating_assessment_result',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='summary_of_procedure',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditprogram',
            name='title_of_procedure',
            field=models.TextField(blank=True),
        ),
    ]
