# Generated by Django 4.1.4 on 2023-07-03 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0007_delete_observations_remove_auditprogram_implications_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditProgramAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=123)),
                ('content', models.FileField(upload_to='audit_files')),
                ('auditprogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditengagement_attachment', to='audit_app.auditprogram')),
            ],
        ),
    ]
