# Generated by Django 4.1.4 on 2023-07-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0008_auditprogramattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditengagementattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=123),
        ),
        migrations.AlterField(
            model_name='auditprogramattachment',
            name='file_name',
            field=models.CharField(blank=True, max_length=123),
        ),
    ]
