# Generated by Django 4.1.4 on 2023-07-05 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0009_alter_auditengagementattachment_file_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprogram',
            name='implications',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
