# Generated by Django 4.1.4 on 2023-07-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0010_auditprogram_implications'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditprogram',
            name='departmentfield',
            field=models.TextField(blank=True, default=0),
        ),
    ]
