# Generated by Django 4.1.4 on 2023-07-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit_app', '0011_auditprogram_departmentfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auditprogram',
            name='departmentfield',
        ),
    ]
