# Generated by Django 4.1.4 on 2023-03-27 06:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('responsible_person', models.TextField()),
                ('responsible_manager', models.TextField()),
                ('status', models.TextField()),
                ('is_critical', models.BooleanField()),
                ('control_objective', models.ManyToManyField(to='master_app.controlobjective')),
                ('departments', models.ManyToManyField(to='master_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryLaws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=30)),
                ('state', models.CharField(default='draft', max_length=30)),
                ('file_name', models.CharField(max_length=123)),
                ('file', models.FileField(upload_to='regulatory_law_file')),
                ('departments', models.ManyToManyField(to='master_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('owner', models.CharField(max_length=30)),
                ('state', models.CharField(default='draft', max_length=30)),
                ('file_name', models.CharField(blank=True, max_length=123)),
                ('file', models.FileField(blank=True, upload_to='policy_file')),
                ('date_approval', models.DateField(default=django.utils.timezone.now)),
                ('policy_edit', models.TextField(blank=True)),
                ('policy_text', models.TextField(max_length=500)),
                ('review_date', models.DateField(default=django.utils.timezone.now)),
                ('departments', models.ManyToManyField(to='master_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='IssueControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_reference_number', models.TextField()),
                ('issue_creation_date', models.DateField()),
                ('issue_status', models.TextField()),
                ('assign_to', models.TextField()),
                ('assign_to_manager', models.TextField()),
                ('short_description', models.TextField()),
                ('propose_action_plan', models.TextField()),
                ('control', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='policy_app.control')),
                ('control_objective', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='master_app.controlobjective')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='policy',
            field=models.ManyToManyField(to='policy_app.policy'),
        ),
        migrations.AddField(
            model_name='control',
            name='regulatory_laws',
            field=models.ManyToManyField(to='policy_app.regulatorylaws'),
        ),
    ]
