# Generated by Django 4.1.4 on 2023-05-27 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0002_regulatorylaws_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='state',
            field=models.CharField(default='Draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='regulatorylaws',
            name='state',
            field=models.CharField(default='Draft', max_length=30),
        ),
    ]
