# Generated by Django 4.1.4 on 2023-06-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0003_alter_policy_state_alter_regulatorylaws_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulatorylaws',
            name='policy',
        ),
    ]
