# Generated by Django 4.1.4 on 2023-07-05 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0004_remove_regulatorylaws_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulatorylaws',
            name='policy',
            field=models.ManyToManyField(to='policy_app.policy'),
        ),
    ]
