# Generated by Django 4.1.4 on 2023-07-07 09:44
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0010_companysetup_departments'),
        ('policy_app', '0005_regulatorylaws_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='assign_to',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='assign_to_manager',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='issue_creation_date',
            field=models.DateField(blank=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='control',
            name='issue_reference_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='propose_action_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='control',
            name='short_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='control_objective',
            field=models.ManyToManyField(blank=True, to='master_app.controlobjective'),
        ),
        migrations.AlterField(
            model_name='control',
            name='departments',
            field=models.ManyToManyField(blank=True, to='master_app.department'),
        ),
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='is_critical',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='policy',
            field=models.ManyToManyField(blank=True, to='policy_app.policy'),
        ),
        migrations.AlterField(
            model_name='control',
            name='regulatory_laws',
            field=models.ManyToManyField(blank=True, to='policy_app.regulatorylaws'),
        ),
        migrations.AlterField(
            model_name='control',
            name='responsible_manager',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='responsible_person',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
