# Generated by Django 4.1.4 on 2023-07-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_app', '0011_companysetup_departments'),
        ('policy_app', '0006_control_assign_to_control_assign_to_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='assign_to',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='assign_to_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='control_objective',
            field=models.ManyToManyField(blank=True, null=True, to='master_app.controlobjective'),
        ),
        migrations.AlterField(
            model_name='control',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, to='master_app.department'),
        ),
        migrations.AlterField(
            model_name='control',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='is_critical',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='issue_creation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='issue_reference_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='policy',
            field=models.ManyToManyField(blank=True, null=True, to='policy_app.policy'),
        ),
        migrations.AlterField(
            model_name='control',
            name='propose_action_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='regulatory_laws',
            field=models.ManyToManyField(blank=True, null=True, to='policy_app.regulatorylaws'),
        ),
        migrations.AlterField(
            model_name='control',
            name='responsible_manager',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='responsible_person',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
