# Generated by Django 4.1.4 on 2023-07-07 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0009_alter_control_issue_creation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='issue_creation_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
