# Generated by Django 4.1.4 on 2023-07-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy_app', '0011_control_issue_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulatorylaws',
            name='file',
            field=models.FileField(blank=True, upload_to='regulatory_law_file'),
        ),
    ]
